### ISSUE TITLE
mobile position off screen

### ISSUE THREAD

**Issue by matthiasg** [shakee93/vue-toasted#23] opened 2017-07-12 11:13 UTC
On the demo site it seems when it comes from the bottom it is not fixed to viewport but the page height, thus appearing beneath the screen area and invisible. at least it did after scrolling around a few times.

**Comment by shakee93** [comment] 2017-07-12 11:53
when you preview it on the desktop browser i have noticed that but on mobile it seems to be working fine. can you please confirm ?

**Comment by matthiasg** [comment] 2017-07-13 12:34
@shakee93 will do. Did not look into code yet, but dont you use position:fixed ?

**Comment by matthiasg** [comment] 2017-07-13 12:35
@shakee93 on chrome on my android it also appears below the visible screen

**Comment by shakee93** [comment] 2017-07-13 17:14
there was a bug before it was fixed now. i have checked it seems to be working fine on the desktop too. can you reproduce ?

**Comment by shakee93** [comment] 2017-07-14 21:01
Closing as inactive

**Closed by shakee93** 2017-07-14 21:01 UTC

**Comment by matthiasg** [comment] 2017-07-18 06:35
Did you update your demo site ? Because it still scrolls away on mobile chrome.

On desktop, it did not work at first either, but when i closed the chrome developer panel it behaved correctly. This might be a bug or unknown behavior with chrome inspector tools on desktop.

**Comment by shakee93** [comment] 2017-07-18 08:16
the demo page was not quite responsive. i just made the fixes. the page is responsive now.

yet still i cannot see the issue you were referring on the demo site with inspector on and off. it seems to work fine. the demo page is now running on the latest version.

if you still have the problem. maybe a snapshot or something might help me to debug.

thanks
