### ISSUE TITLE
className does not seem to work

### ISSUE THREAD

**Issue by amdp** [shakee93/vue-toasted#122] opened 2019-04-19 16:44 UTC
Hi, maybe I didn't understand something in the docs, but when I pass the options of my toast:

```
this.$toasted.show('New user added.', {duration: 1000, className: 'toasts'})
```
duration works, className has no effect, while if I edit it with containerClass it works:

```
this.$toasted.show('New user added.', {duration: 1000, containerClass: 'toasts'})
```

anybody can tell me why? I am using @nuxtjs/toast but I tested it also using pure vue-toasted.

**Comment by shakee93** [comment] 2019-05-17 10:50
it is working, just tested it.. you can either pass a string or array of classes. can you reproduce the code ?

**Comment by amdp** [comment] 2019-05-20 14:57
Would you like to see the repo?

**Comment by shakee93** [comment] 2019-05-20 18:45
would be nice if you can setup a fiddle

**Comment by amdp** [comment] 2019-05-20 22:53
don't know how to do it can you teach me?

**Comment by rockymontana** [comment] 2019-07-03 10:43
We get the exact same issue when trying to set classnames.
The problem is that the theme overrides the custom class rather than letting me overriding the themes CSS. 

As you can see in the screenshot the py-8 class gets overridden by the theme. py-8 is a tailwindcss class for setting padding on the y axis.
![bild](https://user-images.githubusercontent.com/330839/60585452-14b88800-9d90-11e9-9894-22e213da0703.png)

**Comment by WilliamConnatser** [comment] 2019-07-14 18:15
I have the same issue.. the toastr theme CSS is overriding the CSS I'm defining via a custom class.

As a workaround I put !important on every CSS property.

**Comment by rockymontana** [comment] 2019-07-14 19:16
We did that too. I think it’s a really bad solution though 😇

**Comment by amdp** [comment] 2019-07-14 20:24
Same here, !important works

**Comment by mambows** [comment] 2019-07-31 04:16
You can override the style by increasing the specificity of the selector rather than using `!important`, for example:

```css
.toasted.toasted-primary.my-toasted-theme {
  background: #f00;
}
```

**Comment by shakee93** [comment] 2020-05-25 12:53
closing this as could be done with css.

**Closed by shakee93** 2020-05-25 12:53 UTC

**Comment by iamdcj** [comment] 2020-10-15 19:34
I am struggling to apply a custom class selector using the `className` option, it simply does not work. I'm also not sure this should be closed based on the above reason; wrestling with specificity doesn't address the reported issue.

**Comment by sduncan-mbt** [comment] 2021-03-05 00:16
I was having the same issue as you guys. After reading this I did a little testing and by blanking the theme with say `theme: 'none'` I was able to then use my tailwind class as I wanted to with say `className: 'bg-red-500'`

happy days :)
